In [277]:
import os
import pandas as pd
import matplotlib as plt
import numpy as np
import random

In [86]:
#import csv file
csv_path = '../data/arcan-2-develop-none.csv'

#show head of df
df = pd.read_csv(csv_path)
df.head()

parent_sha  \
0  7189ba7f513bced49b18dd95172b43e3c67822f9   
1  7189ba7f513bced49b18dd95172b43e3c67822f9   
2  7189ba7f513bced49b18dd95172b43e3c67822f9   
3  9985d9028f11e200dcb3fe402eb73d343ee92209   
4  9985d9028f11e200dcb3fe402eb73d343ee92209   

                                  child_sha  \
0  9985d9028f11e200dcb3fe402eb73d343ee92209   
1  9985d9028f11e200dcb3fe402eb73d343ee92209   
2  9985d9028f11e200dcb3fe402eb73d343ee92209   
3  f877c6438cfcf18a8e06d33de95e14e113400131   
4  f877c6438cfcf18a8e06d33de95e14e113400131   

                                            old_file  \
0                                    arcan-2/pom.xml   
1          arcan-2/src/main/java/com/arcan/Main.java   
2      arcan-2/src/test/java/com/arcan/MainTest.java   
3                                    arcan-2/pom.xml   
4  arcan-2/src/main/java/com/arcan/data/graphs/de...   

                                            new_file  old_lines  new_lines  \
0                                    arcan-2/pom.xml          0        106   
1          arcan-2/src/main/java/com/arcan/Main.java          0          7   
2      arcan-2/src/test/java/com/arcan/MainTest.java          0         13   
3                                    arcan-2/pom.xml          0         12   
4  arcan-2/src/main/java/com/arcan/data/graphs/de...          0         17   

         old_author  new_author                     when  
0  Ilaria Pigazzini  Darius Sas  2019-09-25 09:17:20 UTC  
1  Ilaria Pigazzini  Darius Sas  2019-09-25 09:17:20 UTC  
2  Ilaria Pigazzini  Darius Sas  2019-09-25 09:17:20 UTC  
3        Darius Sas  Darius Sas  2019-09-27 14:06:24 UTC  
4        Darius Sas  Darius Sas  2019-09-27 14:06:24 UTC

In [87]:
###SHOW SOME STATISTICS
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print(f"Are there any null values: {df.isnull().values.any()}\n")

unique_values = dict(df.nunique())
for key in unique_values.keys(): print(f"Unique {key}: {unique_values[key]}")

print(f"\nFiles re-named with a commit: {len(df[df['old_file'] != df['new_file']])}")

Total rows: 43160
Total columns: 9
Are there any null values: False

Unique parent_sha: 1779
Unique child_sha: 1779
Unique old_file: 3835
Unique new_file: 3835
Unique old_lines: 430
Unique new_lines: 433
Unique old_author: 8
Unique new_author: 8
Unique when: 1770

Files re-named with a commit: 0


In [88]:
##DROP usless columns
df = df.drop(['new_file', 'old_lines', 'new_lines', 'old_lines', 'old_author','when'], axis=1)

In [111]:
#Group files that changed with the same commit and the commit author
df_selected = df.groupby(['parent_sha','child_sha'], group_keys=False, as_index=False).agg({'old_file': list, 'new_author': 'first'})

In [112]:
df_selected

parent_sha  \
0     00117552ddef1a12866a67a83e759e68ca41428d   
1     005600f8e3d0aec24bb92ec88ada1df550cb994e   
2     00599a731d5e665ec136e4889abeb76bdc8a46b0   
3     00c35d5b071abcba3d1faadaf675f71eb01e9c6f   
4     00f4d537a2a8dbb78d70f181945f08fcd5dc6e9c   
...                                        ...   
1774  fef84192d7a8499462d5d4f5ec3c66c2284583bb   
1775  ff2a133ff8b2fad7af018cc8ee8a6384c3162163   
1776  ff5479369df08a1cdff1b92c7f14dd7cafc2fbf0   
1777  ff8e666cecd3c1f5d0eb56427d9d316100be06e4   
1778  ffd48d4356552a76896a5bf68cfdbc25289d68ae   

                                     child_sha  \
0     678b25ae45dfa7dfab3d2de0f68ac355fd3e9ee7   
1     6485d133ad7b2ce8b9135cc1b7334b9b1bfaa614   
2     cffd4ae52f2068fcb68d10c3f556ca26edf6e5f4   
3     13f6663ec37a77f073ee73ef2dd1754f90150104   
4     a5cb3b5d5c97066e001915d2d7535f358e199c28   
...                                        ...   
1774  e8ecae209fa43943e4e36175476c6c724a2a11ab   
1775  20c5390cd770cc3d9e1ed6696fa675fd0acece10   
1776  2a3ead2319546e1c305f6dc5f83f5713fc24f740   
1777  839cfec7855666333653df07323bf7803bcca7c0   
1778  c4184b7d7054204baf3c798c97f96ef001933845   

                                               old_file        new_author  
0     [arcan-2/arcan-core/pom.xml, arcan-2/arcan-cor...            Darius  
1     [arcan-2/src/main/java/com/arcan/SpringMain.ja...        Darius Sas  
2     [arcan-2/arcan-core/src/main/java/com/arcan/pa...            Darius  
3     [arcan-2/arcan-core/src/test/java/com/arcan/da...        Darius Sas  
4     [arcan-2/arcan-core/pom.xml, arcan-2/arcan-cor...            Darius  
...                                                 ...               ...  
1774  [arcan-2/arcan-server/executable/arcan-server....        Darius Sas  
1775  [arcan-2/arcan-cli/pom.xml, arcan-2/arcan-cli/...            Darius  
1776  [arcan-2/src/main/java/com/arcan/ArcanMain.jav...        Darius Sas  
1777            [arcan-2/.github/workflows/develop.yml]  Alessandro Tundo  
1778  [arcan-2/pom.xml, arcan-2/src/main/java/com/ar...        Darius Sas  

[1779 rows x 4 columns]

In [115]:
##DROP now parent_sha and child_sha columns
df_selected = df_selected.drop(['parent_sha', 'child_sha'], axis=1)

In [116]:
df_selected

old_file        new_author
0     [arcan-2/arcan-core/pom.xml, arcan-2/arcan-cor...            Darius
1     [arcan-2/src/main/java/com/arcan/SpringMain.ja...        Darius Sas
2     [arcan-2/arcan-core/src/main/java/com/arcan/pa...            Darius
3     [arcan-2/arcan-core/src/test/java/com/arcan/da...        Darius Sas
4     [arcan-2/arcan-core/pom.xml, arcan-2/arcan-cor...            Darius
...                                                 ...               ...
1774  [arcan-2/arcan-server/executable/arcan-server....        Darius Sas
1775  [arcan-2/arcan-cli/pom.xml, arcan-2/arcan-cli/...            Darius
1776  [arcan-2/src/main/java/com/arcan/ArcanMain.jav...        Darius Sas
1777            [arcan-2/.github/workflows/develop.yml]  Alessandro Tundo
1778  [arcan-2/pom.xml, arcan-2/src/main/java/com/ar...        Darius Sas

[1779 rows x 2 columns]

In [234]:
#get unique filepath
unique_filepath = sorted(list(set(df['old_file'])), key=lambda x: len(x.split('/')))
num_filepath = len(unique_filepath)
print(f"Num files: {num_filepath}")

id_to_file = {file: index for index,file in enumerate(unique_filepath)}

#convert each file into a sparse vector
sparse_vectors = np.diag(np.full(len(unique_filepath), 1)) 

Num files: 3835


In [235]:
sparse_vectors

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [249]:
#compute probability of a file to be change when a commit is done
instances = df_selected['old_file'].tolist()

#count occurencies
prob_mod_file = {}
for instance in instances:
    for file in instance:
        index = id_to_file[file]
        if index not in prob_mod_file.keys():
            prob_mod_file[index] = 1
        else:
            prob_mod_file[index] = prob_mod_file[index] + 1

#divide by the total number of commits
total_commit = len(instances)
for key in prob_mod_file:
    prob_mod_file[key] = prob_mod_file[key]/total_commit

In [309]:
#create randomly instance and target for training
data_size = 10000
x = np.empty([data_size, len(unique_filepath)], dtype=int)
y = np.empty([data_size, len(unique_filepath)], dtype=int)

c = 0
while c < data_size-1:
    for instance in instances:
        if len(instance) == 1: continue
        elif len(instance) == 2:
            num_file_mod = 1
        else:
            num_file_mod = np.random.randint(1, len(instance)-1)

        ids = [id_to_file[file] for file in instance]
        file_mod = 0
        tmp_x = np.zeros([1, len(unique_filepath)])
        tmp_y = np.zeros([1, len(unique_filepath)])
        while file_mod < num_file_mod:
            id = np.random.choice(ids)
            if random.random() > prob_mod_file[id]:
                tmp_x = tmp_x + sparse_vectors[id]
                file_mod += 1
                ids.remove(id)

        assert len(ids) > 0
        tmp_y = np.sum(sparse_vectors[ids],axis=0)
        x[c] = tmp_x
        y[c] = tmp_y
        c+=1
        if c > data_size-1: break
    

In [313]:
np.any(np.sum(x, axis=1)==0)

False

In [315]:
np.any(np.sum(y, axis=1)==0)

False

In [275]:
a = np.array([[3,4],[2,3], [4,6], [7,6]])
print(a) 
b = np.sum(a[[1,2]],axis=0)
b

[[3 4]
 [2 3]
 [4 6]
 [7 6]]


array([6, 9])

In [260]:
a = [2,3,5,6,7,8]
b = 5
a.remove(b)

In [261]:
a

[2, 3, 6, 7, 8]

In [ ]:
#compute max and min depth filepath 
#file_depth = [len(file.split('/')) for file in unique_filepath]
#unique_filepath_split = [file.split('/') for file in unique_filepath]
#print(f"Max file depth: {max(file_depth)}")
#print(f"Min file depth: {min(file_depth)}")


#since the root dir is equal for every file (arcan-2/) it can be the removed --- no information
#for each level associate an id to each of the dirs/files at that level
#id_per_level = {}
#for i in range(0,max(file_depth)):
#    index = 1
#    level = {}
#    for filepath_split in unique_filepath_split:
#        if len(filepath_split) >= i+1:
#            if filepath_split[i] not in level.keys():
#                level[filepath_split[i]] = index
#                index += 1
#            else: continue
#        else: continue
#    id_per_level['level_'+str(i)] = level

#Map each filepath as vector of 13 dimensions